name: appradiotarascamaravatio
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^5.0.2
  http: ^0.12.0+2
  html: ^0.14.0+3
  flutter_html: ^0.11.0
  flutter_widget_from_html: ^0.4.3
  dio: ^3.0.6
  loading: ^1.0.2
  intl: ^0.16.0
  share: ^0.6.3+3
  sqflite: ^1.1.7+3
  firebase_messaging: ^5.1.4
  flutter_svg: ^0.18.0
  flutter_sound: ^2.0.0
  provider: ^3.0.0+1
  flutter_open_whatsapp: ^0.1.2
  firebase_analytics: ^5.0.11
  carousel_slider: ^2.2.1
  path_provider: ^1.6.1
  shared_preferences: ^0.5.6+2
  url_audio_stream: ^1.0.0+3
  flutter_media_notification: ^1.2.6

  file_picker: ^1.9.0+1
  cloud_firestore: ^0.13.5
  firebase_storage: ^3.1.5
  music_player: ^0.1.4
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
      - assets/menu/radio.svg
      - assets/menu/friendship.svg
      - assets/menu/popular.svg
      - assets/menu/music-and-multimedia.svg
      - assets/menu/photo.svg
      - assets/share.svg
      - assets/facebook.svg
      - assets/whatsapp.svg
      - assets/saad.svg
      - assets/blackberry-messenger.svg
      - assets/tarasca.png 
      - assets/Fondoo.png
      - assets/RadTarLogo.png
      - assets/back.svg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Jos
      fonts:
        - asset: assets/fonts/JosefinSans-Regular.ttf
        
    
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
